In [1]:
import numpy as np
import Bayes

from Bayes import *

In [2]:
listOPosts, listClasses = Bayes.loadDataSet()

In [3]:
listOPosts

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [4]:
myVocabList = Bayes.createVocabList(listOPosts)

In [12]:
# myVocabList

In [10]:
# Bayes.setOfWords2Vec(myVocabList, listOPosts[0])

In [11]:
# Bayes.setOfWords2Vec(myVocabList, listOPosts[3])

In [5]:
trainMat = []
for postinDoc in listOPosts:
    trainMat.append(Bayes.setOfWords2Vec(myVocabList, postinDoc))

In [6]:
trainMat

[[1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1],
 [0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0],
 [0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0],
 [0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0]]

In [7]:
listClasses

[0, 1, 0, 1, 0, 1]

In [8]:
 a= len(trainMat[0])

In [9]:
 sum(listClasses) 

3

In [10]:
float(len(trainMat))

6.0

In [11]:
np.zeros(len(trainMat[0]))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
p0V, p1V, pAb = Bayes.trainNB0(trainMat,listClasses) 

In [13]:
p0V

array([0.04166667, 0.04166667, 0.04166667, 0.04166667, 0.04166667,
       0.125     , 0.        , 0.        , 0.04166667, 0.        ,
       0.04166667, 0.04166667, 0.        , 0.04166667, 0.04166667,
       0.        , 0.04166667, 0.04166667, 0.04166667, 0.        ,
       0.04166667, 0.        , 0.        , 0.04166667, 0.        ,
       0.08333333, 0.04166667, 0.        , 0.04166667, 0.        ,
       0.04166667, 0.04166667])

In [15]:
trainMat[1]

[0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0]

In [18]:
p1Num

array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.])

In [ ]:
p0Num = np.zeros(len(trainMat[0]))
p1Num = np.zeros(len(trainMat[0]))
p0Denom = 0.0; p1Denom = 0.0
p1Num += trainMat[1]
p1Denom += sum(trainMat[1])

In [20]:
sum(trainMat[1])

8

In [21]:
p1Num += trainMat[2]

In [23]:
p1Num

array([0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 2., 0., 0., 0., 0., 1., 0.])

In [4]:
# 测试
listOPosts,listClasses = Bayes.loadDataSet()
myVocabList = Bayes.createVocabList(listOPosts)
trainMat=[]
for postinDoc in listOPosts:
    trainMat.append(Bayes.setOfWords2Vec(myVocabList, postinDoc))
p0V,p1V,pAb = Bayes.trainNB0(np.array(trainMat),np.array(listClasses))
testEntry = ['love', 'my', 'dalmation']
thisDoc = np.array(Bayes.setOfWords2Vec(myVocabList, testEntry))
print(testEntry,'classified as: ',Bayes.classifyNB(thisDoc,p0V,p1V,pAb))
testEntry = ['stupid', 'garbage']
thisDoc = np.array(Bayes.setOfWords2Vec(myVocabList, testEntry))
print(testEntry,'classified as: ',Bayes.classifyNB(thisDoc,p0V,p1V,pAb))

['love', 'my', 'dalmation'] classified as:  0
['stupid', 'garbage'] classified as:  1
