In [1]:
import numpy as np
import pandas as pd

from adaboost import *

In [2]:
datMat, classLabels = AdaBoost.loadSimpData(AdaBoost)

In [3]:
datMat

matrix([[1. , 2.1],
        [2. , 1.1],
        [1.3, 1. ],
        [1. , 1. ],
        [2. , 1. ]])

In [4]:
D = np.mat(np.ones((5,1))/5)

In [5]:
D

matrix([[0.2],
        [0.2],
        [0.2],
        [0.2],
        [0.2]])

In [6]:
AdaBoost.buildStump(AdaBoost, datMat, classLabels, D)

({'dim': 0, 'thresh': 1.3, 'ineq': 'lt'},
 matrix([[0.2]]),
 array([[-1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]]))

In [7]:
classifierArray = AdaBoost.adaBoostTrainDS(AdaBoost, datMat, classLabels, 9)

TypeError: data type not understood